[dependencies]
zed_extension_api = "0.7.0"

[lib]
crate-type = ["cdylib"]
path = "src/gdscript.rs"

[package]
edition = "2021"
license = "MIT"
name = "zed_gdscript"
publish = false
version = "0.7.0"

[profile.release]
strip = true
